GET http://localhost:3000/example
// seperating into two different requests

###
GET http://localhost:3000/example/15

###
POST http://localhost:3000/example

{
    "name": "Pramudi",
    "sendingTo":"My admirer"
}